import re
from playwright.sync_api import Page, expect


def test_example(page: Page) -> None:
    page.goto("https://stg.proquro.ai/")
    page.get_by_role("link", name="Sign In").click()
    page.get_by_role("link", name="Securely Login With Email").click()
    page.get_by_role("textbox", name="Email").click()
    page.get_by_role("textbox", name="Email").fill("mobpark@yopmail.com")
    page.get_by_role("textbox", name="Password").click()
    page.get_by_role("textbox", name="Password").fill("Avromandal12345@")
    page.get_by_role("button", name="Log In").click()
    page.get_by_role("button").first.click()
    page.get_by_role("link", name="Cost Centre").click()
    page.get_by_role("button", name="+ Add Cost Center").click()
    page.get_by_role("textbox", name="e.g., CC-PROD-").click()
    page.get_by_role("textbox", name="e.g., CC-PROD-").press("CapsLock")
    page.get_by_role("textbox", name="e.g., CC-PROD-").fill("CB-PROB-01")
    page.get_by_role("button", name="Select type").click()
    page.get_by_role("textbox", name="Search…").fill("")
    page.get_by_role("textbox", name="Search…").click()
    page.get_by_role("textbox", name="Search…").fill("ITEM")
    page.get_by_role("listbox").get_by_text("Item pick up centre").click()
    page.get_by_role("textbox", name="e.g., Production - Main Plant").click()
    page.get_by_role("textbox", name="e.g., Production - Main Plant").fill("MARABATI")
    page.get_by_role("textbox", name="Brief description of what").click()
    page.get_by_role("textbox", name="Brief description of what").fill("T")
    page.get_by_role("textbox", name="Brief description of what").press("CapsLock")
    page.get_by_role("textbox", name="Brief description of what").fill("This is a plant situated in maharashtra")
    page.get_by_role("button", name="Select location").click()
    page.get_by_role("textbox", name="Search…").click()
    page.get_by_role("textbox", name="Search…").fill("ipl")
    page.get_by_text("IPL Technology - Bengaluru Tech Center, Bengaluru, Karnataka,").click()
    page.get_by_role("button", name="Active").click()
    page.get_by_role("option", name="Active", exact=True).click()
    page.get_by_role("button", name="Add Cost Center", exact=True).click()
