import re
from playwright.sync_api import Page, expect


def test_example(page: Page) -> None:
    page.goto("https://stg.proquro.ai/")
    page.get_by_role("link", name="Sign In").click()
    page.get_by_role("link", name="Securely Login With Email").click()
    page.locator("div").nth(2).click()
    page.get_by_role("textbox", name="Email").click()
    page.get_by_role("textbox", name="Email").fill("mobpark@yopmail.com")
    page.locator("div").nth(2).click()
    page.get_by_role("textbox", name="Password").click()
    page.get_by_role("textbox", name="Password").fill("Avromandal12345@")
    page.get_by_role("button", name="Log In").click()
    page.get_by_role("button").first.click()
    page.get_by_role("link", name="Team Management").click()
    page.get_by_role("button", name="Invite Member").click()
    page.get_by_role("textbox", name="Enter first name").click()
    page.get_by_role("textbox", name="Enter first name").fill("krishanu")
    page.get_by_role("textbox", name="Enter last name").click()
    page.get_by_role("textbox", name="Enter last name").fill("saha")
    page.get_by_role("textbox", name="colleague@company.com").click()
    page.get_by_role("textbox", name="colleague@company.com").fill("krishanusaha769@gmail.com")
    page.get_by_role("button", name="Role allocation").click()
    page.get_by_role("textbox", name="Search roles…").click()
    page.get_by_role("textbox", name="Search roles…").fill("Dept")
    page.get_by_role("listbox").get_by_text("Dept User").click()
    page.get_by_role("button", name="Role allocation").click()
    page.get_by_label("Department").click()
    page.get_by_role("textbox", name="Search departments…").click()
    page.get_by_role("textbox", name="Search departments…").fill("da")
    page.get_by_role("listbox").get_by_text("Data Aanalyst").click()
    page.get_by_role("button", name="Location", exact=True).click()
    page.get_by_role("textbox", name="Search locations…").click()
    page.get_by_role("textbox", name="Search locations…").fill("kol")
    page.get_by_text("kolkata, kolkata, wb,").click()
    page.get_by_role("button", name="Send Invitation", exact=True).click()
